letsencrypt_dh_group: /etc/ssl/certs/dhparam.pem
letsencrypt_dh_group_size: 2048
letsencrypt_email: webmaster@{{ inventory_hostname }}
letsencrypt_extra_args:
  - '-d {{ inventory_hostname }}'
letsencrypt_live_dir: /etc/letsencrypt/live/{{ inventory_hostname }}
letsencrypt_renew_hour: 2
letsencrypt_renew_minute: 0
letsencrypt_renew_pre_hook: null
letsencrypt_renew_post_hook: null
