- name: Stop nginx
  service:
    name: nginx
    state: stopped
  ignore_errors: yes
  register: stop_nginx

- name: Create certificate
  command: >
    certbot certonly --standalone --agree-tos
    --email {{ letsencrypt_email }}
    {% for d in letsencrypt_domains %}-d {{ d }} {% endfor %}
    {{ letsencrypt_extra_args | join(' ') }}

- name: Restart nginx
  service:
    name: nginx
    state: started
  when: stop_nginx | succeeded
