---
- name: Disable SSH challenge response authentication
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?ChallengeResponseAuthentication"
    line: ChallengeResponseAuthentication no
    validate: sshd -t -f %s
  notify: restart_sshd

- name: Disable SSH password authentication
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: PasswordAuthentication no
    validate: sshd -t -f %s
  notify: restart_sshd

- name: Disable SSH root login
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: PermitRootLogin no
    validate: sshd -t -f %s
  notify: restart_sshd